const cantones = [
  { label: "Abangares", value: "Esto es una prueba" },
  { label: "Acosta", value: "Acosta" },
  { label: "Alajuela", value: "Alajuela" },
  { label: "Alajuelita", value: "Alajuelita" },
  { label: "Alvarado", value: "Alvarado" },
  { label: "Aserrí", value: "Aserrí" },
  { label: "Atenas", value: "Atenas" },
  { label: "Bagaces", value: "Bagaces" },
  { label: "Barva", value: "Barva" },
  { label: "Belén", value: "Belén" },
  { label: "Buenos Aires", value: "Buenos Aires" },
  { label: "Cañas", value: "Cañas" },
  { label: "Carrillo", value: "Carrillo" },
  { label: "Cartago", value: "Cartago" },
  { label: "Corredores", value: "Corredores" },
  { label: "Coto Brus", value: "Coto Brus" },
  { label: "Curridabat", value: "Curridabat" },
  { label: "Desamparados", value: "Desamparados" },
  { label: "Dota", value: "Dota" },
  { label: "El Guarco", value: "El Guarco" },
  { label: "Escazú", value: "Escazú" },
  { label: "Esparza", value: "Esparza" },
  { label: "Flores", value: "Flores" },
  { label: "Garabito", value: "Garabito" },
  { label: "Goicoechea", value: "Goicoechea" },
  { label: "Golfito", value: "Golfito" },
  { label: "Grecia", value: "Grecia" },
  { label: "Guácimo", value: "Guácimo" },
  { label: "Guatuso", value: "Guatuso" },
  { label: "Heredia", value: "Heredia" },
  { label: "Hojancha", value: "Hojancha" },
  { label: "Jiménez", value: "Jiménez" },
  { label: "LaCruz", value: "LaCruz" },
  { label: "LaUnión", value: "LaUnión" },
  { label: "LeónCortés", value: "LeónCortés" },
  { label: "Liberia", value: "Liberia" },
  { label: "Limón", value: "Limón" },
  { label: "Los Chiles", value: "Los Chiles" },
  { label: "Matina", value: "Matina" },
  { label: "Montes de Oca", value: "Montes de Oca" },
  { label: "Montes de Oro", value: "Montes de Oro" },
  { label: "Mora", value: "Mora" },
  { label: "Moravia", value: "Moravia" },
  { label: "Nandayure", value: "Nandayure" },
  { label: "Naranjo", value: "Naranjo" },
  { label: "Nicoya", value: "Nicoya" },
  { label: "Oreamuno", value: "Oreamuno" },
  { label: "Orotina", value: "Orotina" },
  { label: "Osa Puntarenas", value: "Osa Puntarenas" },
  { label: "Palmares", value: "Palmares" },
  { label: "Paraíso", value: "Paraíso" },
  { label: "Parrita", value: "Parrita" },
  { label: "Pérez Zeledón", value: "Pérez Zeledón" },
  { label: "Poás", value: "Poás" },
  { label: "Pococí", value: "Pococí" },
  { label: "Puntarenas", value: "Puntarenas" },
  { label: "Puriscal", value: "Puriscal" },
  { label: "Quepos", value: "Quepos" },
  { label: "Río Cuarto", value: "Río Cuarto" },
  { label: "San Carlos", value: "San Carlos" },
  { label: "San Isidro", value: "San Isidro" },
  { label: "San Ramón", value: "San Ramón" },
  { label: "San José", value: "San José" },
  { label: "San Mateo", value: "San Mateo" },
  { label: "San Pablo", value: "San Pablo" },
  { label: "San Rafael", value: "San Rafael" },
  { label: "Santa", value: "Santa" },
  { label: "Santa Cruz", value: "Santa Cruz" },
  { label: "Santa Ana", value: "Santa Ana" },
  { label: "Santo Domingo", value: "Santo Domingo" },
  { label: "Sarapiquí", value: "Sarapiquí" },
  { label: "Sarchí", value: "Sarchí" },
  { label: "Siquirres", value: "Siquirres" },
  { label: "Talamanca", value: "Talamanca" },
  { label: "Tarrazú", value: "Tarrazú" },
  { label: "Tibás", value: "Tibás" },
  { label: "Tilarán", value: "Tilarán" },
  { label: "Turrialba", value: "Turrialba" },
  { label: "Turrubares", value: "Turrubares" },
  { label: "Upala", value: "Upala" },
  { label: "Vázquez de Coronado", value: "Vázquez de Coronado" },
  { label: "Zarcero", value: "Zarcero" },
];
export default cantones;
